AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - db/migrate/*
    - bin/bundle
    - db/schema.rb

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false